module Datastoreid
  require 'google/cloud'
  require 'active_support/concern'
  require 'active_model'

  require 'datastoreid/criteria'
  require 'datastoreid/entity/initializable'
  require 'datastoreid/properties'
  require 'datastoreid/persistable/creatable'
  require 'datastoreid/persistable/deletable'
  require 'datastoreid/persistable/savable'
  require 'datastoreid/persistable'
  require 'datastoreid/validatable'
  require 'datastoreid/selectable'
  require 'datastoreid/findable'
  require 'datastoreid/queryable'
  require 'datastoreid/entity'
  require 'datastoreid/errors/datastore_error'
  require 'datastoreid/persistable'
  require 'datastoreid/timestamps'
end
